steps:
  # Step 1: Install Terraform
  - name: hashicorp/terraform:1.5.7
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        terraform init \
          -backend-config="powerful-bounty-469218-q0-tfstate" \
          -backend-config="prefix=terraform/state"

  # Step 2: Terraform plan
  - name: hashicorp/terraform:1.5.7
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan -out=tfplan

  # Step 3: Terraform apply (auto-approve for CI/CD)
  - name: hashicorp/terraform:1.5.7
    id: Terraform Apply
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY

# Store Terraform plan file as an artifact (optional but useful for debugging)
artifacts:
  objects:
    location: gs://$PROJECT_ID-tfstate/artifacts/
    paths: ["tfplan"]

substitutions:
  _REGION: "us-central1"

timeout: 1200s
